# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-13 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRentalRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_time', models.DateTimeField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='countries.Location')),
                ('pick_up_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_up_point', to='countries.Location')),
            ],
        ),
    ]
