# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-16 22:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRentalRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_date', models.DateField(default=datetime.date.today)),
                ('Drop_off_date', models.DateField(default=datetime.date.today)),
                ('pick_up_time', models.TimeField(default='00:00')),
                ('Drop_off_time', models.TimeField(default='00:00')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='countries.Location')),
                ('pick_up_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_up_point', to='countries.Location')),
            ],
        ),
    ]
