# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-16 01:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrentalrequests',
            name='requested_time',
        ),
        migrations.AddField(
            model_name='carrentalrequests',
            name='Drop_off_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='carrentalrequests',
            name='Drop_off_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='carrentalrequests',
            name='pick_up_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='carrentalrequests',
            name='pick_up_time',
            field=models.TimeField(default='00:00'),
        ),
    ]
