# -*- coding: utf-8 -*-
<<<<<<< HEAD:travel/car_rental/migrations/0002_auto_20190220_1603.py
# Generated by Django 1.11.11 on 2019-02-20 16:03
=======
# Generated by Django 1.11.11 on 2019-02-17 17:28
>>>>>>> f120623aea13ef7e14a82f930c9828875bf90f88:travel/car_rental/migrations/0002_carrentalrequests_user_requested.py
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrentalrequests',
            name='user_requested',
<<<<<<< HEAD:travel/car_rental/migrations/0002_auto_20190220_1603.py
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
=======
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
>>>>>>> f120623aea13ef7e14a82f930c9828875bf90f88:travel/car_rental/migrations/0002_carrentalrequests_user_requested.py
        ),
    ]
