# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-13 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=1000)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.City')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.User')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='experience_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments_and_experiences.UserExperience'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user_commented',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.User'),
        ),
    ]
