# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.11 on 2019-02-20 12:57
=======
# Generated by Django 1.11.11 on 2019-02-17 15:32
>>>>>>> f120623aea13ef7e14a82f930c9828875bf90f88
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> f120623aea13ef7e14a82f930c9828875bf90f88
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(help_text='Enter your experiance here.')),
                ('city_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.City')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='experience_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments_and_experiences.UserExperience'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user_commented',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
=======
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=1000)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.City')),
            ],
        ),
>>>>>>> f120623aea13ef7e14a82f930c9828875bf90f88
    ]
