# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-15 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments_and_experiences', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user_commented',
        ),
        migrations.RemoveField(
            model_name='userexperience',
            name='writer',
        ),
    ]
