# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-17 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments_and_experiences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='experience_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comments_and_experiences.UserExperience'),
            preserve_default=False,
        ),
    ]
