# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-18 20:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments_and_experiences', '0003_auto_20190217_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='comments',
            name='experience_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments_and_experiences.UserExperience'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user_commented',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userexperience',
            name='city_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.City'),
        ),
        migrations.AlterField(
            model_name='userexperience',
            name='description',
            field=models.TextField(help_text='Enter your experiance here.'),
        ),
        migrations.AlterField(
            model_name='userexperience',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userexperience',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
