# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-15 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_remove_extendeduser_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extendeduser',
            old_name='password',
            new_name='details',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='name',
        ),
    ]
