# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-15 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20190215_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='user_name',
        ),
    ]
