# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-15 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_remove_extendeduser_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_pictures'),
        ),
    ]
