# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-15 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_extendeduser_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='image',
        ),
    ]
