# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-16 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_travelusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelusers',
            name='email',
            field=models.EmailField(default='noemail', max_length=254),
        ),
        migrations.AddField(
            model_name='travelusers',
            name='first_name',
            field=models.CharField(default='no name selected', max_length=100),
        ),
        migrations.AddField(
            model_name='travelusers',
            name='last_name',
            field=models.CharField(default='no name selected', max_length=100),
        ),
        migrations.AddField(
            model_name='travelusers',
            name='user_name',
            field=models.CharField(default='noemail', max_length=100),
            preserve_default=False,
        ),
    ]
