# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-20 12:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelReservationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('no_of_adults', models.CharField(choices=[('1', '1 adult'), ('2', '2 adults'), ('3', '3 adults'), ('4', '4 adults')], max_length=1)),
                ('requested_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.Hotel')),
                ('user_requested', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
