# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-15 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelreservationrequest',
            name='no_of_adults',
            field=models.CharField(choices=[('1', 'one adult'), ('2', 'two adult')], max_length=1),
        ),
    ]
