# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-21 21:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel_reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelreservationrequest',
            name='user_requested',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
