# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-16 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_reservation', '0002_auto_20190215_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelreservationrequest',
            name='no_of_adults',
            field=models.CharField(choices=[('1', '1 adult'), ('2', '2 adults'), ('3', '3 adults'), ('4', '4 adults')], max_length=1),
        ),
    ]
