# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-16 22:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel_reservation', '0005_remove_hotelreservationrequest_user_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelreservationrequest',
            name='user_requested',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
